---
- name: install redis
  yum: name=redis state=present

- name: upload config file
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    mode: 0640
    force: yes
    backup: yes

- name: start redis server
  systemd:
    name: redis
    state: started
    enabled: yes
